---
# handlers file for reboot

- name: "Reboot"
  shell: sleep 5 && shutdown -r now "Reboot triggered by ansible"
  async: 1
  poll: 0
  ignore_errors: true

- name: "Wait for the machine(s) to be ready again"
  local_action: wait_for host="{{ inventory_hostname }}" state=started delay="15" timeout="60"
  become: false

