---
# handlers file for reboot

- name: 'Reboot'
  ansible.builtin.shell: sleep 5 && shutdown -r now 'Reboot triggered by ansible'
  async: 1
  poll: 0
  failed_when: false
  when:
    - 'not ansible_check_mode | bool'

- name: 'Wait for the machine(s) to be ready again'
  ansible.builtin.wait_for:
    host: "{{ inventory_hostname }}"
    state: 'started'
    delay: '15'
    timeout: '60'
  delegate_to: 'localhost'
  become: false
  when:
    - 'not ansible_check_mode | bool'
